name: flutter_brick_view
description: Flutter Brick View is a light weight package that allows developer to display network images in a brick view. It provides responsive layouts with customizable spacing, max_height, and smooth scrolling.
version: 1.0.1
repository: https://github.com/kei-2k3/flutter-brick-view

license: MIT

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  mocktail_image_network: ^1.2.0
  network_image_mock: ^2.1.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  flutter_test:
    sdk: flutter
